//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFAK.Properties.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChunkNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChunkNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFAK.Properties.Locale.ChunkNames", typeof(ChunkNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Extensions.
        /// </summary>
        internal static string additionalExts {
            get {
                return ResourceManager.GetString("additionalExts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additinal Frame Item.
        /// </summary>
        internal static string additionalFrameItem {
            get {
                return ResourceManager.GetString("additionalFrameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string additionalObjectInstance {
            get {
                return ResourceManager.GetString("additionalObjectInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string appDoc {
            get {
                return ResourceManager.GetString("appDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string appHeader {
            get {
                return ResourceManager.GetString("appHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string binaryFiles {
            get {
                return ResourceManager.GetString("binaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string blurayOptions {
            get {
                return ResourceManager.GetString("blurayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string demoFilePath {
            get {
                return ResourceManager.GetString("demoFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string demoVersion {
            get {
                return ResourceManager.GetString("demoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exeOnly {
            get {
                return ResourceManager.GetString("exeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string extensions {
            get {
                return ResourceManager.GetString("extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string extHeader {
            get {
                return ResourceManager.GetString("extHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string extList {
            get {
                return ResourceManager.GetString("extList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string extraData {
            get {
                return ResourceManager.GetString("extraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string extraPath {
            get {
                return ResourceManager.GetString("extraPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string fontBank {
            get {
                return ResourceManager.GetString("fontBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string fontOffsets {
            get {
                return ResourceManager.GetString("fontOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string frame {
            get {
                return ResourceManager.GetString("frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Effects.
        /// </summary>
        internal static string frameEffects {
            get {
                return ResourceManager.GetString("frameEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Events.
        /// </summary>
        internal static string frameEvents {
            get {
                return ResourceManager.GetString("frameEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Fade In.
        /// </summary>
        internal static string FrameFadeIn {
            get {
                return ResourceManager.GetString("FrameFadeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Fade In Frame.
        /// </summary>
        internal static string frameFadeInFrame {
            get {
                return ResourceManager.GetString("frameFadeInFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Fade Out.
        /// </summary>
        internal static string frameFadeOut {
            get {
                return ResourceManager.GetString("frameFadeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Fade Out Frame.
        /// </summary>
        internal static string frameFadeOutFrame {
            get {
                return ResourceManager.GetString("frameFadeOutFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Handles.
        /// </summary>
        internal static string frameHandles {
            get {
                return ResourceManager.GetString("frameHandles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Header.
        /// </summary>
        internal static string frameHeader {
            get {
                return ResourceManager.GetString("frameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame IPhone Options.
        /// </summary>
        internal static string frameIphoneOptions {
            get {
                return ResourceManager.GetString("frameIphoneOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Layer Effects.
        /// </summary>
        internal static string frameLayerEffects {
            get {
                return ResourceManager.GetString("frameLayerEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Layers.
        /// </summary>
        internal static string frameLayers {
            get {
                return ResourceManager.GetString("frameLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Name.
        /// </summary>
        internal static string frameName {
            get {
                return ResourceManager.GetString("frameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Objects.
        /// </summary>
        internal static string frameObjects {
            get {
                return ResourceManager.GetString("frameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Palette.
        /// </summary>
        internal static string framePalette {
            get {
                return ResourceManager.GetString("framePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Password.
        /// </summary>
        internal static string framePassword {
            get {
                return ResourceManager.GetString("framePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Play Header.
        /// </summary>
        internal static string framePlayHeader {
            get {
                return ResourceManager.GetString("framePlayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Virtual Rect.
        /// </summary>
        internal static string frameVirtualRect {
            get {
                return ResourceManager.GetString("frameVirtualRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Events.
        /// </summary>
        internal static string globalEvents {
            get {
                return ResourceManager.GetString("globalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global String Names.
        /// </summary>
        internal static string globalStringNames {
            get {
                return ResourceManager.GetString("globalStringNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Strings.
        /// </summary>
        internal static string globalStrings {
            get {
                return ResourceManager.GetString("globalStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Value Names.
        /// </summary>
        internal static string globalValueNames {
            get {
                return ResourceManager.GetString("globalValueNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Values.
        /// </summary>
        internal static string globalValues {
            get {
                return ResourceManager.GetString("globalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Bank.
        /// </summary>
        internal static string imageBank {
            get {
                return ResourceManager.GetString("imageBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Offsets.
        /// </summary>
        internal static string imagesOffsets {
            get {
                return ResourceManager.GetString("imagesOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Images.
        /// </summary>
        internal static string menuImages {
            get {
                return ResourceManager.GetString("menuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Header.
        /// </summary>
        internal static string miniHeader {
            get {
                return ResourceManager.GetString("miniHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic Image Table.
        /// </summary>
        internal static string mosaicImageTable {
            get {
                return ResourceManager.GetString("mosaicImageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string musicBank {
            get {
                return ResourceManager.GetString("musicBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string musicOffsets {
            get {
                return ResourceManager.GetString("musicOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string mvTimerBase {
            get {
                return ResourceManager.GetString("mvTimerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectBank {
            get {
                return ResourceManager.GetString("objectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectBank2 {
            get {
                return ResourceManager.GetString("objectBank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectCommon {
            get {
                return ResourceManager.GetString("objectCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectEffects {
            get {
                return ResourceManager.GetString("objectEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectHeader {
            get {
                return ResourceManager.GetString("objectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectName {
            get {
                return ResourceManager.GetString("objectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string objectUnknown {
            get {
                return ResourceManager.GetString("objectUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string otherExts {
            get {
                return ResourceManager.GetString("otherExts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string outputPath {
            get {
                return ResourceManager.GetString("outputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string projectPath {
            get {
                return ResourceManager.GetString("projectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string protection {
            get {
                return ResourceManager.GetString("protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string randomSeed {
            get {
                return ResourceManager.GetString("randomSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string secNum {
            get {
                return ResourceManager.GetString("secNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string shaders {
            get {
                return ResourceManager.GetString("shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string soundBank {
            get {
                return ResourceManager.GetString("soundBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string soundOffsets {
            get {
                return ResourceManager.GetString("soundOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
