//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFAK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFAK.Properties.Locale.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Images.
        /// </summary>
        internal static string dumpImages {
            get {
                return ResourceManager.GetString("dumpImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump MFA.
        /// </summary>
        internal static string dumpMfa {
            get {
                return ResourceManager.GetString("dumpMfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Music.
        /// </summary>
        internal static string dumpMusics {
            get {
                return ResourceManager.GetString("dumpMusics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Sorted.
        /// </summary>
        internal static string dumpSorted {
            get {
                return ResourceManager.GetString("dumpSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Sounds.
        /// </summary>
        internal static string dumpSounds {
            get {
                return ResourceManager.GetString("dumpSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Count.
        /// </summary>
        internal static string frameCount {
            get {
                return ResourceManager.GetString("frameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique FrameItems.
        /// </summary>
        internal static string frameitemCount {
            get {
                return ResourceManager.GetString("frameitemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string gameCopyright {
            get {
                return ResourceManager.GetString("gameCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string gameTitle {
            get {
                return ResourceManager.GetString("gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Images.
        /// </summary>
        internal static string imageCount {
            get {
                return ResourceManager.GetString("imageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Musics.
        /// </summary>
        internal static string musicCount {
            get {
                return ResourceManager.GetString("musicCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dump Folder.
        /// </summary>
        internal static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Frame:.
        /// </summary>
        internal static string readingFrame {
            get {
                return ResourceManager.GetString("readingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sounds.
        /// </summary>
        internal static string soundCount {
            get {
                return ResourceManager.GetString("soundCount", resourceCulture);
            }
        }
    }
}
